language: node_js

node_js:
  - "0.10.38"

sudo: true

before_script:
  - wget https://developer.spotify.com/download/libspotify/libspotify-12.1.51-Linux-x86_64-release.tar.gz
  - tar zxfv libspotify-12.1.51-Linux-x86_64-release.tar.gz
  - cd libspotify-12.1.51-Linux-x86_64-release
  - sudo make install prefix=/usr/local
  - sudo ldconfig
  - cp config.example.json config.json
  - npm install -g coffeelint

script:
  - mocha NODE_ENV=travis
  - coffeelint .
