language: node_js

node_js:
  - "0.10.38"

before_script:
  - sudo apt-get install python-spotify
  - cp config.example.json config.json
  - npm install -g coffeelint

script:
  - mocha NODE_ENV=travis
  - coffeelint .
